name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: Build
        run: |
          # Build for Windows (both 32 and 64 bit)
          GOOS=windows GOARCH=amd64 go build -o gh-iff-windows-amd64.exe
          GOOS=windows GOARCH=386 go build -o gh-iff-windows-386.exe

          # Build for macOS (both Intel and Apple Silicon)
          GOOS=darwin GOARCH=amd64 go build -o gh-iff-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o gh-iff-darwin-arm64

          # Build for Linux (various architectures)
          GOOS=linux GOARCH=amd64 go build -o gh-iff-linux-amd64
          GOOS=linux GOARCH=386 go build -o gh-iff-linux-386
          GOOS=linux GOARCH=arm64 go build -o gh-iff-linux-arm64
          GOOS=linux GOARCH=arm go build -o gh-iff-linux-arm

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF#refs/tags/}"
          gh release create "$tag_name" \
            gh-iff-windows-amd64.exe \
            gh-iff-windows-386.exe \
            gh-iff-darwin-amd64 \
            gh-iff-darwin-arm64 \
            gh-iff-linux-amd64 \
            gh-iff-linux-386 \
            gh-iff-linux-arm64 \
            gh-iff-linux-arm \
            --title "$tag_name" \
            --notes "Release $tag_name"
